# Generated by Django 5.0.1 on 2024-02-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tiitle',
            new_name='title',
        ),
    ]
